# Generated by Django 5.2.7 on 2025-10-02 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_foto_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=200)),
                ('posisi', models.CharField(max_length=200)),
                ('periode_magang', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Berjalan', 'Berjalan'), ('Selesai', 'Selesai')], default='Berjalan', max_length=20)),
                ('nilai_akhir', models.CharField(blank=True, max_length=5, null=True)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.mahasiswa')),
            ],
        ),
    ]
