# Generated by Django 5.2.7 on 2025-10-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magang',
            name='alamat_perusahaan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magang',
            name='bidang_usaha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='magang',
            name='email_supervisor',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='magang',
            name='kontak_wa_supervisor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='magang',
            name='nama_supervisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='magang',
            name='surat_penerimaan',
            field=models.FileField(blank=True, null=True, upload_to='surat_penerimaan/'),
        ),
        migrations.AlterField(
            model_name='magang',
            name='nama_perusahaan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='magang',
            name='periode_magang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='magang',
            name='posisi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
