# Generated by Django 5.2.6 on 2025-10-03 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magang', '0002_magang_alamat_perusahaan_magang_bidang_usaha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magang',
            name='periode_magang',
            field=models.CharField(blank=True, choices=[('2025/2026 Ganjil', 'Semester Ganjil 2025/2026'), ('2025/2026 Genap', 'Semester Genap 2025/2026'), ('2026/2027 Ganjil', 'Semester Ganjil 2026/2027'), ('2026/2027 Genap', 'Semester Genap 2026/2027')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LaporanMagang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_laporan', models.CharField(choices=[('UTS', 'Laporan UTS'), ('UAS', 'Laporan UAS')], max_length=3)),
                ('tanggal_submit', models.DateTimeField(auto_now_add=True)),
                ('profil_perusahaan', models.TextField()),
                ('suasana_kerja', models.TextField()),
                ('budaya_perusahaan', models.TextField()),
                ('jobdesk', models.TextField()),
                ('pengetahuan_bermanfaat', models.TextField(help_text='Apa yang didapatkan dari perkuliahan yang berguna untuk pekerjaan')),
                ('pengetahuan_kurang', models.TextField(help_text='Apa yang berguna pada perusahaan tapi belum didapatkan dalam pembelajaran')),
                ('magang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magang.magang')),
            ],
            options={
                'verbose_name': 'Laporan Magang',
                'verbose_name_plural': 'Laporan Magang',
                'unique_together': {('magang', 'jenis_laporan')},
            },
        ),
    ]
