# Generated by Django 5.2.6 on 2025-10-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magang', '0003_alter_magang_periode_magang_laporanmagang'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaporanMagang',
        ),
    ]
