# Generated by Django 5.2.6 on 2025-10-03 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magang', '0004_delete_laporanmagang'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanMagang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_laporan', models.CharField(choices=[('BULANAN', 'Laporan Bulanan/Kemajuan (UTS)'), ('AKHIR', 'Laporan Akhir (UAS)')], max_length=10)),
                ('bulan_ke', models.PositiveSmallIntegerField(blank=True, help_text='Bulan ke berapa laporan ini dibuat.', null=True)),
                ('tanggal_submit', models.DateTimeField(auto_now_add=True)),
                ('profil_perusahaan', models.TextField(verbose_name='Profil Singkat Perusahaan')),
                ('jobdesk', models.TextField(verbose_name='Jobdesk / Tugas yang Dikerjakan')),
                ('suasana_kerja', models.TextField(verbose_name='Suasana Lingkungan Pekerjaan')),
                ('pengetahuan_bermanfaat', models.TextField(help_text='Apa yang didapatkan dari perkuliahan yang berguna untuk pekerjaan.', verbose_name='Pengetahuan dari Kampus yang Bermanfaat')),
                ('pengetahuan_kurang', models.TextField(help_text='Apa yang berguna pada perusahaan tapi belum didapatkan dalam pembelajaran.', verbose_name='Pengetahuan yang Perlu Ditambahkan')),
                ('dokumen_laporan', models.FileField(blank=True, help_text='Upload file PDF laporan akhir magang (hanya untuk laporan UAS)', null=True, upload_to='dokumen_laporan/', verbose_name='Dokumen Laporan Akhir')),
                ('magang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_magang', to='magang.magang')),
            ],
            options={
                'verbose_name': 'Laporan Magang',
                'verbose_name_plural': 'Laporan Magang',
                'ordering': ['-tanggal_submit'],
                'unique_together': {('magang', 'jenis_laporan', 'bulan_ke')},
            },
        ),
    ]
