# Generated by Django 5.2.7 on 2025-10-03 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magang', '0005_laporanmagang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=200)),
                ('posisi', models.CharField(max_length=200)),
                ('bidang_studi', models.CharField(help_text='Contoh: IT, Desain, Akuntansi', max_length=100)),
                ('deskripsi', models.TextField()),
                ('kualifikasi', models.TextField()),
                ('tanggal_posting', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_perusahaan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lowongan_diposting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
