# Generated by Django 5.2.6 on 2025-10-03 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magang', '0006_lowongan'),
        ('perusahaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magang',
            name='lowongan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perusahaan.lowongan'),
        ),
    ]
