# Generated by Django 5.2.6 on 2025-10-03 13:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahasiswa', '0004_laporanpencarianmagang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerusahaanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=200)),
                ('bidang_usaha', models.CharField(max_length=100)),
                ('alamat', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('deskripsi', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_perusahaan/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('kualifikasi', models.TextField()),
                ('lokasi', models.CharField(max_length=200)),
                ('tipe_magang', models.CharField(choices=[('FULL', 'Full Time'), ('PART', 'Part Time')], max_length=50)),
                ('durasi', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Terbuka'), ('CLOSED', 'Ditutup'), ('FILLED', 'Sudah Terisi')], default='OPEN', max_length=10)),
                ('tanggal_posting', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perusahaan.perusahaanprofile')),
            ],
            options={
                'ordering': ['-tanggal_posting'],
            },
        ),
        migrations.CreateModel(
            name='EvaluasiMagang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('UTS', 'Evaluasi Tengah Semester'), ('UAS', 'Evaluasi Akhir Semester')], max_length=3)),
                ('tanggal_evaluasi', models.DateField(default=django.utils.timezone.now)),
                ('kehadiran', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('kedisiplinan', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('inisiatif', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('kerjasama', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('kemampuan_teknis', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('kelebihan', models.TextField()),
                ('kekurangan', models.TextField()),
                ('saran', models.TextField()),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.mahasiswa')),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perusahaan.perusahaanprofile')),
            ],
            options={
                'ordering': ['-tanggal_evaluasi'],
                'unique_together': {('mahasiswa', 'perusahaan', 'periode')},
            },
        ),
    ]
