# Generated by Django 5.2.6 on 2025-10-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lowongan',
            options={},
        ),
        migrations.RemoveField(
            model_name='lowongan',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Dibuka'), ('CLOSED', 'Ditutup')], default='OPEN', max_length=6),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='tipe_magang',
            field=models.CharField(choices=[('WFO', 'Work From Office'), ('WFH', 'Work From Home'), ('HYBRID', 'Hybrid')], default='WFO', max_length=6),
        ),
        migrations.AlterField(
            model_name='perusahaanprofile',
            name='bidang_usaha',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perusahaanprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='perusahaanprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='foto_profil/'),
        ),
        migrations.AlterField(
            model_name='perusahaanprofile',
            name='nama_perusahaan',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
