# Generated by Django 5.2.7 on 2025-10-02 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('program_studi', models.CharField(max_length=100)),
                ('angkatan', models.IntegerField()),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('kontak_wa', models.CharField(max_length=20)),
                ('email_outlook', models.EmailField(max_length=254)),
                ('bukti_konsultasi', models.FileField(upload_to='dokumen/konsultasi/')),
                ('sptjm', models.FileField(upload_to='dokumen/sptjm/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
