# Generated by Django 5.2.7 on 2025-10-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='foto_profil',
            field=models.ImageField(blank=True, default='foto_profil/default.jpg', null=True, upload_to='foto_profil/'),
        ),
    ]
