# Generated by Django 5.2.7 on 2025-10-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_foto_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/cv/'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='portofolio',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/portofolio/'),
        ),
    ]
