# Generated by Django 5.2.6 on 2025-10-03 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_mahasiswa_cv_mahasiswa_portofolio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanPencarianMagang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_ke', models.PositiveSmallIntegerField(help_text='Nomor urut laporan mingguan Anda.', verbose_name='Minggu Ke-')),
                ('tanggal_lapor', models.DateField(auto_now_add=True, verbose_name='Tanggal Lapor')),
                ('perusahaan_dihubungi', models.TextField(help_text='Sebutkan nama perusahaan, posisi yang dilamar, dan hasilnya.', verbose_name='Perusahaan yang Dihubungi Minggu Ini')),
                ('kendala', models.TextField(blank=True, null=True, verbose_name='Kendala atau Tantangan')),
                ('rencana_minggu_depan', models.TextField(verbose_name='Rencana Aksi Minggu Depan')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_pencarian', to=settings.AUTH_USER_MODEL, verbose_name='Mahasiswa Pelapor')),
            ],
            options={
                'verbose_name': 'Laporan Pencarian Magang',
                'verbose_name_plural': 'Laporan Pencarian Magang',
                'ordering': ['-tanggal_lapor'],
            },
        ),
    ]
